title: D'Mod Journey
email: contact@dmodjourney.com
url: "http://dmodjourney.com"
wooplr: https://www.wooplr.com/user/dhatri-rao/5758112106545152/recommendations
facebook:  https://www.facebook.com/dhatri187
instagram: https://www.instagram.com/dhatrirao/

# Build settings
markdown: kramdown